apiVersion: v1
kind: Pod
metadata:
  name: custom-web
spec:
  volumes:
    - name: site-source
      hostPath:
        path: /run/desktop/mnt/host/c/users/olaka/documents/site
  containers:
    - name: custom-web
      image: nginx:alpine
      volumeMounts:
        - name: site-source
          mountPath: /usr/share/nginx/html
      ports:
        - containerPort: 80
      resources:
         limits:
           memory: 512Mi
           cpu: "1"
         requests:
           memory: 256Mi
           cpu: "0.2"