apiVersion: v1
kind: Pod
metadata:
  name: my-webserver
spec:
  containers:
    - name: my-webserver
      image: nginx:alpine
      ports:
        - containerPort: 80
      resources:
         limits:
           memory: 512Mi
           cpu: "1"
         requests:
           memory: 256Mi
           cpu: "0.2"