apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec: 
  containers:
  - name: myapp    
    image: nginx:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
